### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by ctoveloz** [Hyra/generator-cakephp#2]
yo cakephp

```
... Fetching https://getcomposer.org/composer.phar ...
........................................................Writing composer.phar...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

```

All other generator function Normal.
Thanks.

**Comment by damien-couteillou** [comment]
I have the same error. Don't know why :(

**Comment by branylagaffe** [comment]
Did you have include "php.exe" to your PATH ?

**Comment by damien-couteillou** [comment]
Yes because i can execute the php --help
